<?php

namespace Diver\Database\Query;

use Illuminate\Database\Query\Builder as BaseBuilder;

class Builder extends BaseBuilder
{
    /**
     * Execute the query as a "select" statement.
     *
     * @param  array  $columns
     * @return \Illuminate\Support\Collection
     */
    public function get($columns = ['*'])
    {
        $this->normalizeWhereClauses();
        return parent::get($columns); // TODO: Change the autogenerated stub
    }

    /**
     * Normalise where clauses
     */
    protected function normalizeWhereClauses()
    {
        $this->wheres = collect($this->wheres)->map(function($where) {
            if (!isset($where['column'])) {
                return $where;
            }

            if (str_contains($where['column'], '.')) {
                return $where;
            }

            $where['column'] = $this->from . '.' . $where['column'];

            return $where;
        });
    }
}